version: '3.7'

services:

  redis:
    # image: redis:6-alpine
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  web:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile.api.docker
    # image: fastapi_celery_example_web
    # '/start' is the shell script used to run the service
    # command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - .env/.dev.local
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile.api.docker
    image: 360-energy_web:latest
    command: celery -A main.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env/.dev.local
    depends_on:
      - redis
      - web

  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile.api.docker
    image: 360-energy_web:latest
    # command: rm -f './celerybeat.pid' && celery -A main.celery beat -l info
    command: celery -A main.celery beat -l info
    volumes:
      - .:/app
    env_file:
      - .env/.dev.local
    depends_on:
      - redis
      - web
      # - celery_worker


  # celery_worker:
  #   build:
  #     context: .
  #     dockerfile: ./compose/Dockerfile
  #   image: fastapi_celery_example_celery_worker
  #   command: /start-celeryworker
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env/.dev-sample
  #   depends_on:
  #     - redis
  #     # - db

  # celery_beat:
  #   build:
  #     context: .
  #     dockerfile: ./compose/Dockerfile
  #   image: fastapi_celery_example_celery_beat
  #   command: /start-celerybeat
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env/.dev-sample
  #   depends_on:
  #     - redis
  #     # - db

  # flower:
  #   build:
  #     context: .
  #     dockerfile: ./compose/Dockerfile
  #   image: fastapi_celery_example_celery_flower
  #   command: /start-flower
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env/.dev-sample
  #   ports:
  #     - 5557:5555
  #   depends_on:
  #     - redis
  #     # - db



  # mongo_db:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.mongo
  #   volumes:
  #     - $PWD/data_mongo:/data/db
  #     - $PWD/data_mongo:/var/www/html
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 123


